#!/bin/sh

a=$1
op=$2
b=$3

re='^[+-]?[0-9]+([.][0-9]+)?$'
if ! [[ $a =~ $re ]] ; then
   echo "error: Not a number, Enter a number next time :D" >&2; exit 1
fi

re='^[+-]?[0-9]+([.][0-9]+)?$'
if ! [[ $b =~ $re ]] ; then
   echo "error: Not a number, Enter a number next time :D" >&2; exit 1
fi

case $op in
        +)echo "scale=4;$a+$b" | bc;;
        -)echo "scale=4;$a-$b" | bc;;
        *)echo "scale=4;$a*$b" | bc;;
        /)echo "scale=4;$a/$b" | bc;;
esac
